all:
  hosts:
    gate_rpi:
      ansible_host: 192.168.1.14

    center_rpi:
      ansible_host: 192.168.1.13

    entrance_rpi:
      ansible_host: 192.168.1.15

    garage_rpi:
      ansible_host: 192.168.1.16

    behind_rpi:
      ansible_host: 192.168.1.17

    left_rpi:
      ansible_host: 192.168.1.18
