---
- name: Debug Camera Name
  debug:
    msg: "Attempting to start service for camera: {{ cam_name }}"


- name: Ensure git is installed
  become: yes
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone or update CCTV repository
  git:
    repo: "{{ git_repo }}"
    dest: "{{ git_dest }}"
    version: main
    force: yes

# --- NEW TASK: Deploy config.ini ---
- name: copy CCTV configuration
  copy:
    src: "../config.ini"        # Make sure this file is in your Ansible project folder
    dest: "/home/pi/cctv/config.ini"
    owner: pi
    group: pi
    mode: '0644'
  register: config_file        # We track if the file changed

# --- deploy credentials ---
- name: copy CCTV credentials
  copy:
    src: "../credentials/recorder/credentials.env"        # Make sure this file is in your Ansible project folder
    dest: "/etc/cctv/credentials.env"
    owner: pi
    group: pi
    mode: '0644'
  register: credentials.env        # We track if the file changed


- name: Restart CCTV recorder service
  become: yes
  systemd:
    name: "cctv-video-recorder@{{ cam_name }}.service"
    state: restarted
    enabled: yes
    daemon_reload: yes

